sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t fladago/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true fladago/docker-react npm run test -- --coverage

deploy: 
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-367354732818"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
